### ISSUE TITLE
please, a more complete example?

### ISSUE THREAD

**Issue by lsjack93** [viniciussanchez/blockui-vcl#1]
i can not make it work, the way i imagine it!

**Comment by viniciussanchez** [comment]
This project will aid in blocking a screen. It is similar to creating a form in showmodal. The form will not appear and the background will be darker. See the dialogs4delphi component for a better example ... https://github.com/viniciussanchez/dialogs4delphi
Notice that the dialog box has been "highlighted" thanks to the block-ui component

**Comment by viniciussanchez** [comment]
Hello, did you understand?

**Comment by lsjack93** [comment]
yeah, totally!
now i understand how it works, thank you!
